2018-07-12 09:34:25,563 - ERROR - Exception Information : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 153, in test01_api
    api_messages=api_message)
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/api_test/api_request.py", line 218, in api_requests
    api_hope, api_status, response)
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/api_test/api_request.py", line 122, in print_log
    self.log.info('11.接口返回 : {0}'.format(response[1]))
TypeError: 'int' object is not subscriptable

2018-07-12 09:34:25,564 - ERROR - 1. 接口编号 : 1_4 | 接口名称 : Team_Construction - 是否是团队员工 
2018-07-12 09:34:25,565 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:27,990 - ERROR - 1. 接口编号 : 1_8 | 接口名称 : Team_Construction - 部门列表 
2018-07-12 09:34:27,991 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:28,571 - ERROR - 1. 接口编号 : 1_11 | 接口名称 : Team_Construction - 职位列表 
2018-07-12 09:34:28,572 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:28,757 - ERROR - 1. 接口编号 : 1_12 | 接口名称 : Team_Construction - 职位更新 
2018-07-12 09:34:28,757 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:28,958 - ERROR - 1. 接口编号 : 1_13 | 接口名称 : Team_Construction - 职位详情 
2018-07-12 09:34:28,959 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:29,330 - ERROR - 1. 接口编号 : 1_15 | 接口名称 : Personal - 职位-申请（借用） 
2018-07-12 09:34:29,331 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:29,551 - ERROR - 1. 接口编号 : 1_16 | 接口名称 : Team_Construction - 职位申请-处理 
2018-07-12 09:34:29,552 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:29,751 - ERROR - 1. 接口编号 : 1_17 | 接口名称 : Team_Construction - 员工列表 
2018-07-12 09:34:29,752 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:29,879 - ERROR - Exception Information : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 153, in test01_api
    api_messages=api_message)
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/api_test/api_request.py", line 218, in api_requests
    api_hope, api_status, response)
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/api_test/api_request.py", line 122, in print_log
    self.log.info('11.接口返回 : {0}'.format(response[1]))
TypeError: 'int' object is not subscriptable

2018-07-12 09:34:29,882 - ERROR - 1. 接口编号 : 1_18 | 接口名称 : Team_Construction - 员工任免 
2018-07-12 09:34:29,882 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:30,052 - ERROR - 1. 接口编号 : 1_19 | 接口名称 : Team_Construction - 员工列表 
2018-07-12 09:34:30,053 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:30,225 - ERROR - 1. 接口编号 : 1_20 | 接口名称 : Team_Construction - 员工列表 
2018-07-12 09:34:30,225 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:31,140 - ERROR - 1. 接口编号 : 1_24 | 接口名称 : Personal - 职位邀请-处理（借用） 
2018-07-12 09:34:31,141 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

2018-07-12 09:34:31,292 - ERROR - 1. 接口编号 : 1_25 | 接口名称 : Team_Construction - 员工任免 
2018-07-12 09:34:31,292 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 219, in test01_api
    assert False != api_check_result[0]
AssertionError

2018-07-12 09:34:31,466 - ERROR - 1. 接口编号 : 1_26 | 接口名称 : Team_Construction - 员工主动退出 
2018-07-12 09:34:31,467 - ERROR - 2. 错误信息 : Traceback (most recent call last):
  File "/Users/xiaojingyuan/PycharmProjects/Appium/YunluFramework_API/testcase/SpaceAPI/TestSpaceApi.py", line 168, in test01_api
    assert status_code == api_status
AssertionError

